import { defineConfig, type Plugin } from 'vite';
import { appendFileSync, mkdirSync } from 'node:fs';
import { resolve } from 'node:path';

const here = import.meta.dirname;
const LOG_DIR = resolve(here, 'logs');

/**
 * Writes the browser's session log straight to `portal/logs/*.ndjson`.
 *
 * The alternative was a keypress that downloads a file, which loses the run
 * whenever the tab reloads, crashes, or the person forgets — and the run worth
 * having is usually the one that just went wrong. Streaming it to disk means
 * every session is captured by default and readable from the repo, which is
 * what makes latency work possible at all.
 *
 * `apply: 'serve'` — this exists only under `npm run dev`. A production build
 * has no such endpoint, and the client only calls it behind `import.meta.env.DEV`.
 */
function sessionLogPlugin(): Plugin {
  return {
    name: 'portal-session-log',
    apply: 'serve',
    configureServer(server) {
      server.middlewares.use('/__log', (req, res) => {
        if (req.method !== 'POST') {
          res.statusCode = 405;
          res.end();
          return;
        }
        const chunks: Buffer[] = [];
        req.on('data', (c: Buffer) => chunks.push(c));
        req.on('end', () => {
          try {
            const { sessionId, header, lines } = JSON.parse(
              Buffer.concat(chunks).toString('utf8'),
            ) as { sessionId: string; header?: unknown; lines: unknown[] };
            // Session ids are generated by our own client, but this endpoint is
            // reachable by anything on localhost — so refuse anything that
            // could escape the log directory rather than trusting the name.
            if (!/^[A-Za-z0-9-]{1,80}$/.test(sessionId)) {
              res.statusCode = 400;
              res.end('bad session id');
              return;
            }
            mkdirSync(LOG_DIR, { recursive: true });
            const body = [...(header ? [header] : []), ...lines]
              .map((l) => JSON.stringify(l))
              .join('\n');
            appendFileSync(resolve(LOG_DIR, `portal-${sessionId}.ndjson`), body + '\n');
            res.statusCode = 204;
            res.end();
          } catch (err) {
            // Never let a logging failure take the dev server down.
            server.config.logger.warn(`[session-log] ${String(err)}`);
            res.statusCode = 500;
            res.end();
          }
        });
      });
    },
  };
}

/**
 * Receives the raw camera and Lucy recordings and appends them to
 * `portal/logs/*.webm` (see recorder.ts).
 *
 * Binary and append-only, for the same reason the log streams: chunks arrive
 * every couple of seconds and a crashed tab should still leave a playable file
 * behind. Serve-only, like the log endpoint.
 */
function streamRecordingPlugin(): Plugin {
  return {
    name: 'portal-stream-recording',
    apply: 'serve',
    configureServer(server) {
      server.middlewares.use('/__rec', (req, res) => {
        if (req.method !== 'POST') {
          res.statusCode = 405;
          res.end();
          return;
        }
        const url = new URL(req.url ?? '/', 'http://localhost');
        const session = url.searchParams.get('session') ?? '';
        const name = url.searchParams.get('name') ?? '';
        // Both halves land in a filename, so neither may contain a path.
        if (!/^[A-Za-z0-9-]{1,80}$/.test(session) || !/^[A-Za-z0-9-]{1,32}$/.test(name)) {
          res.statusCode = 400;
          res.end('bad session or name');
          return;
        }
        const chunks: Buffer[] = [];
        req.on('data', (c: Buffer) => chunks.push(c));
        req.on('end', () => {
          try {
            mkdirSync(LOG_DIR, { recursive: true });
            appendFileSync(
              resolve(LOG_DIR, `portal-${session}-${name}.webm`),
              Buffer.concat(chunks),
            );
            res.statusCode = 204;
            res.end();
          } catch (err) {
            server.config.logger.warn(`[stream-recording] ${String(err)}`);
            res.statusCode = 500;
            res.end();
          }
        });
      });
    },
  };
}

export default defineConfig({
  plugins: [sessionLogPlugin(), streamRecordingPlugin()],
  build: {
    rollupOptions: {
      input: {
        main: resolve(here, 'index.html'),
        // Side-by-side transition comparison, driven by the real transition
        // module rather than a copy of it (PRD §4.1).
        transitions: resolve(here, 'transitions.html'),
        // Close-detection strictness ladder, driven by the real geometry
        // module rather than a copy of it (PRD §2.2.1).
        closure: resolve(here, 'closure.html'),
        // Same comparison as `closure`, but on the live camera — the strictness
        // gets picked here, on real hands.
        tune: resolve(here, 'tune.html'),
        // The getting-started choreography, camera-only so refining it costs
        // no Lucy generation time.
        tutorial: resolve(here, 'tutorial.html'),
      },
    },
  },
});
